# =============================
# SERVER CONFIG
# =============================
server.port=3000

# =============================
# SPRING APPLICATION
# =============================
spring.application.name=api-gateway

# =============================
# GLOBAL CORS CONFIG
# =============================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# =============================
# ROUTES CONFIGURATION
# =============================
# 1. Product Service
spring.cloud.gateway.routes[0].id=product-service 
spring.cloud.gateway.routes[0].uri=http://localhost:3001 
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**


spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=http://localhost:3002
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/inventory/**

spring.cloud.gateway.routes[2].id=customer-service
spring.cloud.gateway.routes[2].uri=http://localhost:3003
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/customers/**

spring.cloud.gateway.routes[3].id=identity-service
spring.cloud.gateway.routes[3].uri=http://localhost:3004
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[4].id=loyalty-service
spring.cloud.gateway.routes[4].uri=http://localhost:3005
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/loyalty/**

spring.cloud.gateway.routes[5].id=reporting-service
spring.cloud.gateway.routes[5].uri=http://localhost:3006
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/reports/**

spring.cloud.gateway.routes[6].id=order-service
spring.cloud.gateway.routes[6].uri=http://localhost:3007
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.routes[7].id=promotion-service
spring.cloud.gateway.routes[7].uri=http://localhost:3008
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/promotions/**

spring.cloud.gateway.routes[8].id=delivery-service
spring.cloud.gateway.routes[8].uri=http://localhost:3009
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/delivery/**

spring.cloud.gateway.routes[9].id=payment-service
spring.cloud.gateway.routes[9].uri=http://localhost:3011
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/payments/**

spring.cloud.gateway.routes[10].id=shift-service
spring.cloud.gateway.routes[10].uri=http://localhost:3010
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/shifts/**
spring.cloud.gateway.routes[10].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[11].id=AI-service
spring.cloud.gateway.routes[11].uri=http://localhost:3012
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/ai/**

spring.cloud.gateway.routes[12].id=franchise-service
spring.cloud.gateway.routes[12].uri=http://localhost:3013
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/franchises/**,/api/requests/**

logging.level.org.springframework.cloud.gateway=DEBUG

management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true
management.server.port=3000

spring.security.oauth2.client.provider.cognito.issuerUri=${ISSUER_URI}

# WebSocket route for inventory service
spring.cloud.gateway.routes[13].id=inventory-service-ws
spring.cloud.gateway.routes[13].uri=ws://localhost:3002
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/inventory/ws-inventory/**
spring.cloud.gateway.routes[13].order=-1