spring.application.name=shift-service
server.port=3010

spring.datasource.url=jdbc:postgresql://dpg-d6p32jpr0fns73e37jog-a.oregon-postgres.render.com:5432/shift_db_zsnw
spring.datasource.username=shift_db
spring.datasource.password=ZhY3Z12CumOZEEY6qci2UvVEnM9eSq5Q

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=60000

# T?i ?u JPA
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true