# ================================
# SERVER CONFIG
# ================================
server.port=3006
spring.application.name=report-service

# ================================
# SERVICE URLS CONFIG
# ================================
# Order Service
services.order-service.url=http://localhost:3007
services.order-service.path=/api/orders

# Product Service
services.product-service.url=http://localhost:3001
services.product-service.path=/api/products

# Customer Service
services.customer-service.url=http://localhost:3005
services.customer-service.path=/api/loyalty

# # Branch Service (Franchise)
# services.branch-service.url=http://localhost:3002
# services.branch-service.path=/api/branches

# ================================
# WEBCLIENT CONFIG
# ================================
webclient.connection-timeout=5000
webclient.read-timeout=10000
webclient.max-connections=500
webclient.max-memory-size=16777216

# ================================
# LOGGING
# ================================
logging.level.com.example.reportservice=DEBUG
logging.level.org.springframework.web.reactive=INFO