# ================================
# SERVER CONFIG
# ================================
server.port=3006
spring.application.name=report-service

# ================================
# SERVICE URLS CONFIG   
# ================================
services.order-service.url=http://localhost:3007
services.order-service.path=/api/orders

# ================================
# WEBCLIENT CONFIG
# ================================
webclient.connection-timeout=10000
webclient.read-timeout=60000
webclient.max-connections=500
webclient.max-memory-size=16777216

# ================================
# LOGGING
# ================================
logging.level.com.example.reportservice=DEBUG
logging.level.org.springframework.web.reactive=INFO
