# ================================
# SERVER CONFIG
# ================================
server.port=3006
spring.application.name=report-service


# ================================
# ORDER DATABASE (Render)
# ================================
spring.datasource.order.url=jdbc:postgresql://dpg-d6ghni1drdic73c6u9l0-a.singapore-postgres.render.com:5432/group_03
spring.datasource.order.username=group_03_user
spring.datasource.order.password=b0d0wXijbTZChwN3ipQbBmiKiHy8TwHu
spring.datasource.order.driver-class-name=org.postgresql.Driver


# ================================
# PRODUCT DATABASE,FRANCHISE DATABASE (Render)
# ================================
spring.datasource.product.url=jdbc:postgresql://dpg-d6fg4615pdvs739n1csg-a.singapore-postgres.render.com/franchise_db_74u0?sslmode=require
spring.datasource.product.username=franchise_user
spring.datasource.product.password=FNLbwoIxRBofbo4fblMhULaUHqGbThi7
spring.datasource.product.driver-class-name=org.postgresql.Driver

# ================================
# JPA CONFIG
# ================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ================================
# CONNECTION POOL (optional)
# ================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000