server:
  port: 3004

spring:
  application:
    name: identity-access-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - openid
              - phone
            redirect-uri: https://d84l1y8p4kdic.cloudfront.net
        provider:
          cognito:
            issuerUri: ${issuerURI}
            user-name-attribute: ${ATTRIBUTE}

aws:
  region: ${REGION}
  accessKeyId: ${ACCESS_KEY_ID}
  secretAccessKey: ${SECRET_ACCESS_KEY}
  cognito:
    userPoolId: ${USER_POOL_ID}
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}
    domain: https://ap-southeast-1bxpfambw9.auth.ap-southeast-1.amazoncognito.com
    googleCallbackUrl: http://localhost:3004/api/auth/google/callback
    frontendUrl: http://localhost:5173

app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:3000
      - https://yourdomain.com

jwt:
  secret: ${SECRET_KEY}