server:
  port: 3005

spring:
  application:
    name: loyalty-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC

# CẤU HÌNH LOYALTY RULES VÀ TIERS
loyalty:
  rule:
    amount-per-point: 10000.0 # 10,000 VND = 1 điểm
  tiers:
    silver: 500               # Mốc điểm lên hạng Bạc
    gold: 1000                # Mốc điểm lên hạng Vàng
    platinum: 2000            # Mốc điểm lên hạng Bạch Kim
    diamond: 3000             # Mốc điểm lên hạng Kim Cương