server:
  port: 3011
spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    #      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
#    validate-on-migrate: true

momo:
  partner_code: MOMO
  return_url: ${RETURN_URL}
  end_point: ${END_POINT}
  ipn_url: ${IPN_URL}
  access_key: ${ACCESS_KEY}
  secret_key: ${SECRET_KEY}
  request_type: captureWallet

# VNPay Config
vnpay:
  tmn-code: ${TMN_CODE}
  hash-secret: ${HASH_SECRET}
  payment-url: ${PAYMENT_URL}
  return-url: http://localhost:3011/api/payments/vnpay-return
  ipn-url: https://abc123.ngrok-free.app/api/payments/vnpay-ipn
  version: 2.1.0
  command: pay
  currency-code: VND
  locale: vn
